build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - make test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-cloudcontrol
    when:
      branch: master

plugin:
  name: cloudControl
  desc: Deploys or updates a project on cloudControl
  type: deploy
  image: plugins/drone-cloudcontrol
  labels:
    - cloud
    - control
