[[constraint]]
  name = "github.com/drone-plugins/drone-git-push"
  version = "0.1.0"

[[constraint]]
  name = "github.com/fern4lvarez/gocclib"
  version = "0.3.0"

[prune]
  go-tests = true
  unused-packages = true
